### ISSUE TITLE
What about merge ilua into luaish?

### ISSUE THREAD

**Issue by starwing** [stevedonovan/luaish#1]
hi steve :-)

I just found there is a ilua in LuaForWIndows, and there is a wiki entry for that in lua-users.org. I found that's interesting. is there any plan to add ilua to luaish?

**Comment by stevedonovan** [comment]
The big difference is that ilua removes the need for '=' before expressions; it does this by first trying to compile as an expression, and then falling back as a statement.  It's a cool option for inclusion in luaish, but I want to ensure that one always gets a sensible error message - which is tricky since if an expression fails to compile, it will be recompiled as a statement.

luaish currently is just Unix, chiefly because I don't have an easy way to do tab-completion on Windows. If such a mechanism was available, I would like to make it more cross-platform.  (Actually, on Windows, the best bet would be a graphical fake console since there is a terrible ingrained fear of black boxes in Windows people ;))

**Comment by starwing** [comment]
that's a pity :-(

Windows do not have luaposix and linenoise...

so it's diffcult to port it to windows.

but I just like do some small things in interactive lua, e.g. a tiny calculator.

so maybe I will try to write a lua5.2 compatilble ilua with mapm support :-(

thx~
